services:
  app-myfin:
    volumes:
      - ./myfinance/statement/static:/myfinance/static
      - ./myfinance/statement/migrations:/myfinance/migrations
      - ./myfinance/media/:/myfinance/media/
      - ./myfinance/logs/:/myfinance/logs/
    build:
      context: .
    ports:
      - "8111:8111"
    environment:
      DEBUG: "${MYFIN_DEBUG}"
      DJANGO: "${MYFIN_DEBUG}"
      SECRET_KEY: "${MYFIN_SECRET_KEY}"
      HOSTS: "${MYFIN_DJANGO_HOSTS}"
      CORS_ALLOWED_ORIGINS: "${MYFIN_CORS_ALLOWED_ORIGINS}"
      CSRF_TRUSTED_ORIGINS: "${MYFIN_CSRF_TRUSTED_ORIGINS}"
      MYSQL_USER: "${MYFIN_MYSQL_USER}"
      MYSQL_PASSWORD: "${MYFIN_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYFIN_MYSQL_DATABASE}"
      MYSQL_HOST: "${MYFIN_MYSQL_HOST}"
      MYSQL_PORT: "${MYFIN_MYSQL_PORT}"
      URL: "VAULT_URL"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${MYFIN_DJANGO_ACCESS_TOKEN_EXPIRE_MINUTES}"
      ALGORITHM: "${MYFIN_DJANGO_ALGORITHM}"
      TRANSACTION_CLASSIFIER_URL: "${MYFIN_TRANSACTION_CLASSIFIER_URL}"
      TRANSACTION_CLASSIFIER_PORT: "${MYFIN_TRANSACTION_CLASSIFIER_PORT}"
    depends_on:
      - mysql-myfin
    networks:
      myfin-net:
        ipv4_address: 172.18.0.3

    command: >
      sh -c "
        python manage.py collectstatic --no-input --verbosity 0 &&
        daphne -b 0.0.0.0 -p 8000 myfinance.asgi:application
      "

  mysql-myfin:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYFIN_MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYFIN_MYSQL_USER}"
      MYSQL_PASSWORD: "${MYFIN_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYFIN_MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-myfin-vol:/var/lib/mysql
    networks:
      myfin-net:
        ipv4_address: 172.18.0.2

  nginx-myfin:
    image: nginx:1.19.0-alpine
    volumes:
      - ./myfinance/statement/static/:/static/
      - ./myfinance/media/:/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - app-myfin
    networks:
      - myfin-net

  redis-myfin:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      myfin-net:
        ipv4_address: 172.18.0.4

  transaction-classifier:
    build:
      context: ./transaction_classifier
    container_name: transaction-classifier
    ports:
      - "8112:8112"
    environment:
      SECRET_KEY: "${MYFIN_SECRET_KEY}"
      ALGORITHM: "${TRANSACTION_CLASSIFIER_ALGORITHM}"
      TOKEN_URL: "${TRANSACTION_CLASSIFIER_TOKEN_URL}"
      SERVER_URL: "${TRANSACTION_CLASSIFIER_SERVER_URL}"
      URL: "${TRANSACTION_CLASSIFIER_URL}"

      REDIS_HOST: "${TRANSACTION_CLASSIFIER_REDIS_HOST}"
      REDIS_PORT: "${TRANSACTION_CLASSIFIER_REDIS_PORT}"
      REDIS_DB: "${TRANSACTION_CLASSIFIER_REDIS_DB}"
      REDIS_KEY: "${TRANSACTION_CLASSIFIER_REDIS_KEY}"
      OAUTH2_TOKEN_URL: "${TRANSACTION_CLASSIFIER_OAUTH2_TOKEN_URL}"
      CLIENT_ID: "${TRANSACTION_CLASSIFIER_CLIENT_ID}"
      CLIENT_SECRET: "${TRANSACTION_CLASSIFIER_CLIENT_SECRET}"
    volumes:
      - ./transaction_classifier:/app
    depends_on:
      - app-myfin
    networks:
      myfin-net:
        ipv4_address: 172.18.0.6
    restart: unless-stopped

networks:
  myfin-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  mysql-myfin-vol:
