version: '3.7'

services:
  app-myfin:
    volumes:
      - ./myfinance/statement/static:/myfinance/static
      - ./myfinance/media/:/myfinance/media/
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: "${DJANGO_SECRET}"
      DJANGO_DEBUG: "${DJANGO_DEBUG}"
      DJANGO_HOSTS: "${DJANGO_HOSTS}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${MYSQL_PORT}"
    depends_on:
      - mysql-myfin

  mysql-myfin:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-myfin-vol:/var/lib/mysql
      
  nginx-myfin:
    image: nginx:1.19.0-alpine
    volumes:
      - ./myfinance/statement/static/:/static/
      - ./myfinance/media/:/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app-myfin

volumes:
  mysql-myfin-vol: