version: '3.9'

services:
  app-myprod:
    volumes:
      - ./myprod/atividades/static:/myprod/static
      - ./myprod/media/:/myprod/media/
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "8121:8111"
    environment:
      DEBUG: "${MYPROD_DEBUG}"
      DJANGO: "${MYPROD_DEBUG}"
      SECRET_KEY: "${MYPROD_SECRET_KEY}"
      ALLOWED_HOSTS: "${MYPROD_DJANGO_HOSTS}"
      CSRF_TRUSTED_ORIGINS: "${MYPROD_CORS_ALLOWED_ORIGINS}"
      CORS_ALLOWED_ORIGINS: "${MYPROD_CSRF_TRUSTED_ORIGINS}"
      MYSQL_USER: "${MYPROD_MYSQL_USER}"
      MYSQL_PASSWORD: "${MYPROD_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYPROD_MYSQL_DATABASE}"
      MYSQL_HOST: "${MYPROD_MYSQL_HOST}"
      MYSQL_PORT: "${MYPROD_MYSQL_PORT}"
      URL: "VAULT_URL"
    depends_on:
      - mysql-myprod
    networks:
      myprod-net:
        ipv4_address: 172.20.0.3

  mysql-myprod:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYPROD_MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYPROD_MYSQL_USER}"
      MYSQL_PASSWORD: "${MYPROD_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYPROD_MYSQL_DATABASE}"
    ports:
      - "3307:3306"
    volumes:
      - mysql-myprod-vol:/var/lib/mysql
    networks:
      myprod-net:
        ipv4_address: 172.20.0.2

  nginx-myprod:
    image: nginx:1.19.0-alpine
    volumes:
      - ./myprod/atividades/static/:/static/
      - ./myprod/media/:/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
    depends_on:
      - app-myprod
    networks:
      - myprod-net

networks:
  myprod-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  mysql-myprod-vol:
