#!/bin/bash

# DEFINIR VARIÁVEIS
DATE=$(date +'%Y-%m-%d');
ACTUAL_IMAGE=$(docker image ls | grep app-myfin | grep -v bkp | awk -F' ' '{print $3}');
BKP_IMAGE="docker_myfinance_app-myfin-bkp-v$DATE"
BASEDIR='/home/fernando/git/prod/docker_myfinance';

# PARAR SERVIÇO
sudo systemctl stop myfinance.service;

# ATUALIZAR APLICAÇÃO
cd $BASEDIR;
cd myfinance;
git pull;
cd ..

# BACKUP IMAGEM ANTIGA
docker tag docker_myfinance_app-myfin $BKP_IMAGE;
docker image rm docker_myfinance_app-myfin;
docker-compose up -d;
docker-compose down;

# INICIAR O SERVIÇO
sudo systemctl start myfinance.service;

sleep 20;

# SALVAR A VERSÂO
export $(cat .env | grep -v ^# | xargs);
SQL_COMMANT="SELECT version FROM statement_version ORDER BY id DESC LIMIT 1";
VERSION=$(mysql -u"$MYFIN_MYSQL_USER" -p"$MYFIN_MYSQL_PASSWORD" -h"$MYFIN_MYSQL_LOCAL" -D "$MYFIN_MYSQL_DATABASE" -P "$MYFIN_MYSQL_LOCAL_PORT" -e "$SQL_COMMAND" -sN);
NEW_VERSION=$(echo "$VERSION" | awk -F '.' '{print $1"."$2"."$3+1}')
SQL_COMMAND="INSERT INTO statement_version (version, date) VALUES('$NEW_VERSION', '$DATE')";
mysql -u"$MYFIN_MYSQL_USER" -p"$MYFIN_MYSQL_PASSWORD" -h"$MYFIN_MYSQL_LOCAL" -D "$MYFIN_MYSQL_DATABASE" -P "$MYFIN_MYSQL_LOCAL_PORT" -e "$SQL_COMMAND";